# Example of docker-based Database Server.
# Start using: docker-compose up -d
# Stop using: docker-compose down
version: '2.4'
services:
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - pomo
  web-server:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:  
      - "80:3000"
    networks:
      - pomo

networks:
    pomo:
      driver: bridge